export const BASE_URL = ""
export const USERS_URL = "/api/user" 
export const PRODUCTS_URL = "/api/products" 
export const AUTH_URL = "/api/auth" 
export const ORDERS_URL = "/api/orders" 
export const CART_URL = "/api/cart" 
export const PAYPAL_URL = "/api/config/paypal" 
